import type { Metadata } from "next";
import { Alice, Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "../components/layout/navbar";
import Footer from "../components/layout/footer";
import CookieConsent from "../components/layout/cookies2";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        
        <Footer/> 
       <CookieConsent/>
      </body>
    </html>
  );
}
